version: "3"
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    ports:
    - "27018:27017"
    volumes:
      - ./docker/mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongo