version: "3"
services:
  mongo:
    image: mongo:4.4.4
    ports:
    - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=Gmd_db
    volumes:
      - ./docker/mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mongo